[package]
name = "pasty"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rocket = "0.5.0-rc.1"
rocksdb = "0.17.0"
serde = "1.0.130"
nanoid = "0.4.0"
url = "2.2.2"